service: AiDemo

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds:
      - !Ref ServerlessSecurityGroup
    subnetIds:       - subnet-00f677a7f7cdea980

functions:
  hello:
    handler: src/lambda/hello.handler
    events:
      - httpApi:
          path: /hello
          method: get

resources:
  Resources:
    ServerlessSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for serverless functions
        VpcId: vpc-0956ba067263f706b
        SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0

plugins:
  - serverless-esbuild
