AWSTemplateFormatVersion: '2010-09-09'
Description: CDN resources for AI Demo

Parameters:
  ProjectName:
    Type: String
    Default: AiDemo
    Description: Name of the project

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment
  
  WebsiteBucketName:
    Type: String
    Description: Name of the S3 bucket for website files
  
  ApiEndpoint:
    Type: String
    Description: API Gateway endpoint URL

Resources:
  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName}-${Environment}-OAI"

  # Bucket policy for CloudFront access using OAI
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${WebsiteBucketName}/*"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${WebsiteBucketName}.s3.amazonaws.com"
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
          - DomainName: !Select [2, !Split ["/", !Ref ApiEndpoint]]
            Id: ApiGateway
            OriginPath: !Sub "/${Environment}"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1.2]
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - PathPattern: '/ai'
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            TargetOriginId: ApiGateway
            ForwardedValues:
              QueryString: true
              Headers:
                - 'Authorization'
                - 'Content-Type'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: https-only
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        HttpVersion: http2
        IPV6Enabled: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-distribution"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  WebsiteUrl:
    Description: "CloudFront distribution URL for the website"
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WebsiteUrl"
      
  DistributionId:
    Description: "CloudFront distribution ID"
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DistributionId"
      
  CloudFrontOAI:
    Description: "CloudFront Origin Access Identity"
    Value: !Ref CloudFrontOAI
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontOAI"