AWSTemplateFormatVersion: '2010-09-09'
Description: Storage resources for AI Demo

Parameters:
  ProjectName:
    Type: String
    Default: AiDemo
    Description: Name of the project

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment

Resources:
  # S3 Bucket for all static website files Creation.
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-website-bucket"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # CloudFront Origin Identity (OAI)
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName}-${Environment}-OAI"

  # Bucket policy for CloudFront access using OAI
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: "1"
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub "${WebsiteBucket.Arn}/*"
          - Sid: "2"
            Effect: Allow
            Principal:
              CanonicalUser: "a5a9c93abf90afd9a2b02c5c5c7c4167b22deaf5"
            Action: 's3:GetObject'
            Resource: !Sub "${WebsiteBucket.Arn}/*"

Outputs:
  WebsiteBucketName:
    Description: "Name of the S3 bucket for website files"
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WebsiteBucketName"
  
  WebsiteBucketArn:
    Description: "ARN of the S3 bucket for website files"
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WebsiteBucketArn"
    
  CloudFrontOAI:
    Description: "CloudFront Origin Access Identity"
    Value: !Ref CloudFrontOAI
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontOAI"