AWSTemplateFormatVersion: '2010-09-09'
Description: Storage resources for AI Demo

Parameters:
  ProjectName:
    Type: String
    Default: AiDemo
    Description: Name of the project

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment

Resources:
  # S3 Bucket for all static website files Creation.
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-website-bucket"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  WebsiteBucketName:
    Description: "Name of the S3 bucket for website files"
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WebsiteBucketName"
  
  WebsiteBucketArn:
    Description: "ARN of the S3 bucket for website files"
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WebsiteBucketArn"