AWSTemplateFormatVersion: '2010-09-09'
Description: This is a copy of the AiDemo using the template for creation.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0956ba067263f706b
    Description: ID of the existing company VPC
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-00f677a7f7cdea980
    Description: List of existing subnet IDs for deployment

Resources:
  # Your resources will go here

Outputs:
  # Your outputs will go here
